### PR TITLE
use `lodash.*` modules instead of monolithic `lodash`

### PR DESCRIPTION
**Pull request by ahdinosaur**
also lodash should be a dependency not a devDependency.

same reasoning as https://github.com/gajus/redux-immutable/pull/5, also `redux-immutable` tests were failing due to the dep / devDep bug.

### CODE REVIEW

**Comment by gajus** [comment]
Hi @ahdinosaur, Thank for the PR.

Please see https://github.com/gajus/canonical/commit/746a02606795035388b185290b13e49357966a8c.

To the best of my understanding, the way that you are proposing to use lodash, including separate lodash modules (`lodash.forEach`, etc.) will actually increase the bundle size because bundler is unable to recognise that `lodash/collection/forEach` and `lodash.forEach` is the same package. Therefore, the proper way to avoid duplication is using `lodash` dependency and constructing custom lodash package, e.g. https://github.com/gajus/canonical/blob/master/src/utils.js.

**Comment by gajus** [comment]
This is a problem with `lodash` package itself (@jdalton). Again, correct me if I am wrong, but if `lodash` main package did not come as a bundle of all functions and instead had each of them as a "dependency", then your proposal to use `lodash.*` packages would indeed make sense because a bundler would almost always recognise the duplication.

**Comment by ahdinosaur** [comment]
hey @gajus :smile: 

> To the best of my understanding, the way that you are proposing to use lodash, including separate lodash modules (lodash.forEach, etc.) will actually increase the bundle size because bundler is unable to recognise that lodash/collection/forEach and lodash.forEach is the same package.

this is true if one requires `lodash` as a dependency to use `lodash/collection/forEach`, but [for my projects i avoid using `lodash` and only use `lodash.*` modules](https://github.com/holodex/app/blob/9bff1b5ba97e8573903141d9f3a35d7262c7eb0f/package.json#L81-L97) so i can get the de-duplication and separate versioning. (inspired by [amp](https://blog.andyet.com/2015/01/07/modularizing-underscorejs) and [lodash@3](https://blog.andyet.com/2015/03/25/amped-down))

> Therefore, the proper way to avoid duplication is using lodash dependency and constructing custom lodash package, e.g. https://github.com/gajus/canonical/blob/master/src/utils.js.

i must admit i don't understand how this would provide de-duplication for those of us exclusively using `lodash.*` modules in our projects.

**Comment by gajus** [comment]
@ahdinosaur You are assuming that everyone uses `lodash.*` approach to load modules. The majority of developers are lazy and will use "lodash" itself. This is very easy to proof.
- https://www.npmjs.com/package/lodash 14000+ dependencies
- https://www.npmjs.com/package/lodash.foreach under 100 dependencies.

**Comment by ahdinosaur** [comment]
hehe, to be honest i can't be bothered with what most developers do if it means worse functionality, i'm happy to maintain a fork or write my own module. thanks for your work and prompt replies, be well. :cake:

**Pull request closed without merging**
